String parseHomePage();
String parseControlPage();
String parseConfigurePage();

String footer = "<!-- Footer -->"
                "<footer class='w3-bottom w3-center w3-black w3-padding-small w3-opacity w3-hover-opacity-off'>"
                "<div class='w3-xlarge'>"
                "<a href='https://github.com/ZGoode/Irrigation-System'><i class='fa fa-github w3-hover-opacity'></i></a>"
                "<a href='http://linkedin.com/in/zachary-goode-724441160'><i class='fa fa-linkedin w3-hover-opacity'></i></a>"
                "</div>"
                "</footer>"
                ""
                "</body>"
                "</html>";

String header = "<!DOCTYPE html>"
                "<html>"
                "<title>IOT Cloud</title>"
                "<meta charset='UTF-8'>"
                "<meta name='viewport' content='width=device-width, initial-scale=1'>"
                "<link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>"
                "<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato'>"
                "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>"
                "<style>"
                "body,h1,h2,h3,h4,h5,h6 {font-family: 'Lato', sans-serif;}"
                "body, html {"
                "height: 100%;"
                "color: #777;"
                "line-height: 1.8;"
                "}"
                "/* Create a Parallax Effect */"
                ".bgimg{"
                "background-attachment: fixed;"
                "background-position: center;"
                "background-repeat: no-repeat;"
                "background-size: cover;"
                "}"
                "/* Background Picture */"
                ".bgimg{"
                "background-image: url('%BACKGROUND_IMAGE%');"
                "min-height: 100%;"
                "}"
                ".w3-wide {letter-spacing: 10px;}"
                ".w3-hover-opacity {cursor: pointer;}"
                ".slidecontainer {"
                "width: 100%;}"
                ".slider {"
                "-webkit-appearance: none;"
                "width: 100%;"
                "height: 25px;"
                "background: #d3d3d3;"
                "outline: none;"
                "opacity: 0.7;"
                "-webkit-transition: .2s;"
                "transition: opacity .2s;}"
                ".slider:hover {"
                "opacity: 1;}"
                ".slider::-webkit-slider-thumb {"
                "-webkit-appearance: none;"
                "appearance: none;"
                "width: 25px;"
                "height: 25px;"
                "background: #4CAF50;"
                "cursor: pointer;}"
                ".slider::-moz-range-thumb {"
                "width: 25px;"
                "height: 25px;"
                "background: #4CAF50;"
                "cursor: pointer;}"
                "</style>"
                "<body>"
                "<!-- Navbar (sit on top) -->"
                "<div class='w3-top'>"
                "<div class='w3-bar' id='myNavbar'>"
                "<a href='Home' class='w3-bar-item w3-button'>HOME</a>"
                "<a href='Control' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-user'></i> CONTROL</a>"
                "<a href='Configure' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-cogs'></i> CONFIGURE</a>"
                "<a href='https://github.com/ZGoode/Irrigation-System' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-th'></i> ABOUT</a>"
                "<a href='/WifiReset' class='w3-bar-item w3-button w3-hide-small w3-right w3-hover-red'>WIFI RESET</a>"
                "<a href='/FactoryReset' class='w3-bar-item w3-button w3-hide-small w3-right w3-hover-red'>FACTORY RESET</a>"
                "</div>"
                "</div>";

String homePage = "<!-- First Parallax Image with Logo Text -->"
                  "<div class='bgimg w3-display-container w3-opacity-min' id='home'>"
                  "<div class='w3-display-middle' style='white-space:nowrap;'>"
                  "<p><span class='w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity'>IOT<span class='w3-hide-small'> IRRIGATION</span> SYSTEM</span></p>"
                  "<p><span class='w3-center w3-padding-large w3-black w3-large w3-wide w3-animate-opacity'>CURRENT<span class='w3-hide-small'> MOISTURE:</span> %MOISTURELEVEL%%</span></p>"
                  "</div>"
                  "</div>";

String controlPage = "<div class='bgimg w3-display-container w3-opacity-min' id='home'>"
                     "<div class='w3-display-middle' style='white-space:nowrap;'>"
                     "<div class='w3-black'>"
                     "<form class='w3-container' action='/updateControl' method='get'><h2>System Settings:</h2>"
                     "<div>Target Moisture (%): <span id='demo1'></span><p class='slidecontainer'><input type='range' min='0' max='100' value='%TARGETVALUE%' class='slider' id='myRange1' name='target'></p></div>"
                     "<div>Trigger Value (%): <span id='demo2'></span><p class='slidecontainer'><input type='range' min='0' max='100' value='%TRIGGERVALUE%' class='slider' id='myRange2' name='trigger'></p></div>"
                     "<script>"
                     "var slider1 = document.getElementById('myRange1');"
                     "var output1 = document.getElementById('demo1');"
                     "output1.innerHTML = slider1.value;"
                     "slider1.oninput = function() {"
                     "output1.innerHTML = this.value;}"
                     "</script>"
                     "<script>"
                     "var slider2 = document.getElementById('myRange2');"
                     "var output2 = document.getElementById('demo2');"
                     "output2.innerHTML = slider2.value;"
                     "slider2.oninput = function() {"
                     "output2.innerHTML = this.value;}"
                     "</script>"
                     "<button class='w3-button w3-block w3-grey w3-section w3-padding' type='submit'>Save</button>"
                     "</form>"
                     "</div>"
                     "</div>"
                     "</div>";

String configurePage = "<div class='bgimg w3-display-container w3-opacity-min' id='home'>"
                       "<div class='w3-display-middle' style='white-space:nowrap;'>"
                       "<div class='w3-black'>"
                       "<form class='w3-container' action='/updateConfig' method='get'><h2>System Config:</h2>"
                       "<p><label>User ID (for this interface)</label><input class='w3-input w3-border w3-margin-bottom' type='text' name='userid' value='%USERID%' maxlength='20'></p>"
                       "<p><label>Password </label><input class='w3-input w3-border w3-margin-bottom' type='password' name='stationpassword' value='%STATIONPASSWORD%'></p>"
                       "<p><label>OTA Password </label><input class='w3-input w3-border w3-margin-bottom' type='password' name='otapassword' value='%OTAPASSWORD%'></p>"
                       "<p><label>Blynk Authenticator </label><input class='w3-input w3-border w3-margin-bottom' type='text' name='blynkauthenticator' value='%BLYNKAUTHENTICATOR%'></p>"
                       "<button class='w3-button w3-block w3-grey w3-section w3-padding' type='submit'>Save</button>"
                       "</form>"
                       "</div>"
                       "</div>"
                       "</div>";

String parseHomePage() {
  return header + homePage + footer;
}

String parseControlPage() {
  return header + controlPage + footer;
}

String parseConfigurePage() {
  return header + configurePage + footer;
}
